version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=javalabtwo
    ports:
      - "6452:5432"
    restart: unless-stopped